apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: testcluster
  region: us-west-2

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.small
    desiredCapacity: 3
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        imageBuilder: true
